:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

= Program Options - trying again!


== Introduction

See the following for an introduction on Posix command-line utility syntax:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02[Utility syntax guidelines]

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_01[Utility Argument Syntax]

There are existing very mature C# command line parsers, but they do not fit well with dependency injection. The 
approach with this parser is to provide an interface `ICommandLineParser` that allows specifying and parsing options.

Command line programs require options (arguments starting with a minus or double minus). There may also be one _verb_.

Options are of the following types:

. *Boolean*. These options are either present or not.
. *String*. These options take a number of string parameters (default 1)
. *Integer*. These options take a number of integers.
. *Double*. These options take a number of doubles.

== Short options

*Short options* are options specified by a single character such as the `*-m*` (_message_) option of `git commit`.

----
git commit -m "updated header files"
----


Boolean options can be combined so that `*myprog -abc*` is the same as `*myprog -a -b -c*`. Options combined in a single word
in this way are referred to as grouped options. The word itself is referred to as an _options group_.

A short option can take one or more parameters. Where it does, the option may still appear as part of an options group but it must
be the final option in the group.

The first or only parameter of a short option may immediately follow the option letter with no intervening space even if the
short option is at the end of an option group.

== Long options

*Long options* are options starting with a double minus and are typically a whole word rather than just a single letter. An
example is the `--interactive` option of git rebase:

----
git rebase --interactive 4205AC4
----

Long options _typically_ have a precisely equivalent single letter option.

Long options cannot form option groups.

Where a long option takes a parameter, there must be a space between the option and the parameter. *However* an equals
sign is sometimes allowed between the long option and its parameter **with no intervening spaces**.

== End of options

A double-dash (`--`) marks the end of options - any argument after the double-dash is not an option.

== Verbs

A command that uses a verb has a single word not starting with a dash that controls the function of the command. Git 
is the classic example here: the verbs are `init`, `add`, `commit` etc. Verbs are not quite the same thing as options
but the implementation described below includes them. 

* only one verb is permitted per command (e.g. `git commit add -u` doesn't make sense since it has two verbs).
* each verb takes a different set of options

== Options with optional parameters

Optional options are sometimes used but are a dubious concept. An optional option can confused with an operand.
In the first pass, options with optional parameters are not implemented.

== Quotes

Windows passes the entire command line to a process (including the name of the command itself) - the process startup functions then break
the command line into words before calling `main(int argc, char**argv)` (C or C++) or `Main(string[] args)` (C#). Double quotes can be
used to form a single argument from a group of space separated words - however, double quotes are always removed from `args` (or `argv`)
so that, for example: "That's me Fred"and Jim is converted to two arguments:

----
That's me Fredand
Jim
----

Single quotes are passed unchanged from the command-line to `args`. Bash, when running on Windows, provides the illusion that single-quotes
can also be used to group words into a single argument. However, all it does is to replace single-quotes with double-quotes before starting
the command.

[You can see this in C# like this:

----
Console.WriteLine($"Command line: {Environment.CommandLine}");
----
]

Bash on Windows will also pass a quoted argument when escaping the space between two or more arguments with a backslash:

----
MyProg a\ b\ c
----

We may wish to process single-quotes specially at a later date.

== Mutual exclusion

Some options are mutually exclusive. For example in Unix *grep*, *-E* *-F* and *-P* are mutually exclusive.


== Implementation

=== Specifying short and long options 

Each option attribute takes two parameters - a single `char` parameter and a `string`. Obviously the `char` parameter
is for the single letter option and the `string` parameter for the double-dash long option. 

To omit a short option, specify `'\0'`. To omit a long option specify an empty string.


=== Version and BuildInfo 

Utilities typically support `--version` and `--help` options. Both can be supported automatically using the `[Help]`
and `[Version]` attribute classes. Additionally `AmsArgParse` supports the BuildInfo option
which will provide informaticd on about the build number and link date and time.



=== Mutual exclusion


=== Verbs

If a program allows _verbs_, it should call `ICommandLineParser.AllowVerbs(<verbset>)` where `<verbset>` is a list comma-separated
list of strings specifying the verbs allowed.

For example:

----
var options = new CommandLineParser();
options.AllowVerbs("add", "commit", "init");
----

Unless there is a call to AllowVerbs, no verbs will be permitted. 

=== Adding an option specification

To specify a valid option, we must decide on a "name" or handle for an option - this name is not necessarily the same as the string
used on the command line to set the option althought it can be. For example we can call the SpecifyOption method as follows:

----
var options = new CommandLineParser();
options.SpecifyOption("filename", 'f', "file", 1);
options.ParseCommandLine(args);

var filenameOption = GetOption("filename");
if (filenameOption.Count == 1)
{
	string filename = filenameOption.Value;
}
----

==== Repeated options

Some options can be repeated in the same command line:

----
myprog -i input1.txt -i input1.txt -o output1.html
----

==== An option's specification

|===
| short name		| a single character
| long name			| a string
| type				| a System.Type
| value				| a string - only if isRepeatable is false
| values 			| a List<string>  - only if isRepeatable is true
| verbs				| a string[] array - verbs for which this option is allowed. If empty then this option is for any verb.
| Count				| the number of times the option was found when parsing the command-line
| index				| the index - only if isRepeatable is false
| indices			| a List<int> indicating the positions in which the option was found
| isRepeatable 		| true or false;
|===

----
myprog --author
----


== The future

Other types of option may be implemented. Ideas include

* Integer ranges e.g.

----
cut -c 1-3,8-10 file.txt
----

* Ranges with a double-dot like `git commit` ranges:

----
prog -h fa5ea7f6..78a53c98
prog -h fa5ea7f6 .. 78a53c98
----

* Options based on tuples +
e.g. we might want to represent latitude longitude pair as a tuple.


